### ISSUE TITLE
Capa Service Producto

### ISSUE THREAD

**Issue by DarioRv** [21Enzo17/repo-tp2#73]
# Capa Service Producto
1. En el paquete service cree las interfaces necesarias para declarar los métodos.
La declaración de métodos abstractos dentro de las interfaces deben permitir implementar en las clases de
`service.imp` las siguientes acciones:
 - Listar
 - Guardar
 - Modificar
 - Eliminar
 - Buscar (por algún criterio)
 - Recuperar un objeto del model. 
2. En el paquete `service.imp` cree las clases que implementen las interfaces.
3. En las clases del paquete `controller` y `service.imp` aplique la inyección de dependencia utilizando la
anotación `@Autowired`.
4. Continúe con la **documentación** del código.

![Thymeleaf](https://img.shields.io/badge/-Thymeleaf-green?logo=thymeleaf) ![Java](https://img.shields.io/badge/-Java-red)

**Comment by 21Enzo17** [comment]
Se completo los requerimientos de la issue, se finalizo el commit y procedo a cerrar la rama
