### ISSUE TITLE
Capa Service Paseo

### ISSUE THREAD

**Issue by DarioRv** [21Enzo17/repo-tp2#75]
# Capa Service Paseo
1. En el paquete service cree las interfaces necesarias para declarar los métodos.
La declaración de métodos abstractos dentro de las interfaces deben permitir implementar en las clases de
`service.imp` las siguientes acciones:
 - Listar
 - Guardar
 - Modificar
 - Eliminar
 - Buscar (por algún criterio)
 - Recuperar un objeto del model. 
2. En el paquete `service.imp` cree las clases que implementen las interfaces.
3. En las clases del paquete `controller` y `service.imp` aplique la inyección de dependencia utilizando la
anotación `@Autowired`.
4. Continúe con la **documentación** del código.

![Thymeleaf](https://img.shields.io/badge/-Thymeleaf-green?logo=thymeleaf) ![Java](https://img.shields.io/badge/-Java-red)

**Comment by JohanRosero** [comment]
Capa Service implementada para paseos, a la espera de definición del método de Busqueda para finalizar la tarea. Se probó y esta totalmente funcional.

**Comment by DarioRv** [comment]
> A la espera de definición del método de Busqueda para finalizar la tarea.

La implementación de un método de busqueda por algún criterio puede desarrollarse como una barra de busqueda o lista de filtros.

**Comment by JohanRosero** [comment]
Método de busqueda desarrollado con éxito, se da por finalizada la tarea, los resultados se pueden ver y probar el la rama Service-Paseos.
