### ISSUE TITLE
Capa Repository Paseos

### ISSUE THREAD

**Issue by DarioRv** [21Enzo17/repo-tp2#85]
# Capa Repository Paseos
1. Agregue las dependencias necesarias en el archivo pom.xml:
- Spring boot starter data jpa
- MySql conector java.
2. Agregue en el archivo `application.properties` las propiedades necesarias para el acceso y configuración
de base de datos. 
**Ejemplo para mysql:**
```
spring.datasource.url=jdbc:mysql://localhost:3306/bdejemplo2023?serverTimeZone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.generate-ddl= true
spring.jpa.hibernate.ddl-auto=create-drop
```
3. Modificar el nombre de paquete model a **entity**. Realizar el mapeo utilizando anotaciones pertenecientes
al paquete **jakarta.persistence** (**Entity, Table, Id, Column, OneToMany, OneToOne** etc.)
4. En cada clase se debe indicar que atributo será la clave primaria (**Id**), agregar un atributo de tipo Long
con nombre id.
5. Por cada atributo indicar el nombre de la columna (**Column**).
6. Realice el mapeo de las relaciones:
- Servicio – Empleado (el servicio solo tiene un único encargado (empleado)).
Empleado es una clase que representa a un empleado encargado de un servicio.
En cada clase agregue un atributo de tipo boolean denominado estado, este atributo indica si el objeto está
activo o no. Si se quiere eliminar un objeto se utilizará el estado = false, cuando se crea un nuevo objeto el
estado siempre tiene valor true.
7. Crear el paquete **repository** y cree las interfaces necesarias. Identifique los métodos para realizar las
consultas de los datos.
- Mostrar los servicios según el día seleccionado.
8. En el menú de navegación agregue una opción denominada “Gestión de datos”, donde se muestren las
opciones para dar de alta las diferentes entidades (redirige al respectivo formulario abm de cada entidad).
9. Continúe con la documentación del código.

![Java](https://img.shields.io/badge/-Java-red) ![Thymeleaf](https://img.shields.io/badge/-Thymeleaf-green?logo=thymeleaf) ![JPA](https://img.shields.io/badge/-Java%20Persistence%20API-brown) ![Hibernate](https://img.shields.io/badge/-Hibernate-blue?logo=hibernate) ![MySQL](https://img.shields.io/badge/-MySQL-white?logo=mysql)

**Comment by JohanRosero** [comment]
Recibido, se inicia la implementación de lo indicado, Crearé una nueva rama y la publicaré oportunamente.
Tarea en progreso.
